
name = "my-blog-app"
compatibility_date = "2024-08-28"
pages_build_output_dir = "./dist"


kv_namespaces = [
  { binding = "<MY_NAMESPACE>", id = "<KV_ID>" }
]

[env.preview]
name = "my-blog-preview"

kv_namespaces = [
  { binding = "<MY_NAMESPACE>", id = "<STAGING_KV_ID>" }
]